### ISSUE TITLE
mvid version error

### ISSUE THREAD

**Issue by chortonhsi** [mdejong/AVAnimator#18]
used the utility MvidMovieMaker provided to convert mov to mvid and when trying to use the mvid in our ios app with AVAnimator, getting this:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'only .mvid files version 2 or newer can be used, you must -upgrade this .mvid from version 1'

**Comment by mdejong** [comment]
You can use the "mvid upgrade FILENAME" command, but make sure that you are using the most recent version of mvidmoviemaker build from the github source to make sure you will not run into further problems. This version issue cannot be worked around automatically, you have to make sure to have the latest version of both the encoder and the decoder in the client otherwise it will not work on 64 bit hardware.

**Comment by chortonhsi** [comment]
Thank you!  I’ll create a build from github and will then run mvid upgrade

**Comment by mdejong** [comment]
Yeah, sorry about this detail. It is a nasty issue having to do with 64 bit support for ARM 64 devices. There was just no easy way to keep it working without a forced upgrade in the encoder.
